### ISSUE TITLE
vnc installation failure.

### ISSUE THREAD

**Issue by rajesh-rajagopal** [megamsys/vnc_server#9]
Jan 24 16:37:05 VirtEngine1 node[30518]:     at Module.load (module.js:487:32)
Jan 24 16:37:05 VirtEngine1 node[30518]:     at tryModuleLoad (module.js:446:12)
Jan 24 16:37:05 VirtEngine1 node[30518]:     at Function.Module._load (module.js:438:3)
Jan 24 16:37:05 VirtEngine1 node[30518]: The worker #8 has disconnected
Jan 24 16:37:05 VirtEngine1 node[30518]: Worker 8 died :(
Jan 24 16:37:05 VirtEngine1 node[30518]: module.js:471
Jan 24 16:37:05 VirtEngine1 node[30518]:     throw err;
Jan 24 16:37:05 VirtEngine1 node[30518]:     ^
Jan 24 16:37:05 VirtEngine1 node[30518]: **Error: Cannot find module 'socket.io'**
Jan 24 16:37:05 VirtEngine1 node[30518]:     at Function.Module._resolveFilename (module.js:469:15)

brucem@VirtEngine1:/usr/share/detio/virtenginevnc$ **grep -rnw '.' -e "socket.io"**
./public/vnc.html:40:        <script src="http://localhost:8090/socket.io/socket.io.js"></script>
./lib/vnc_tenant.js:26:var socketio = require('socket.io');
./lib/vnc_tenant.js:72: * Export the socket io's listen function.
./node_modules/cliff/node_modules/winston/README.md:754:3. [socket.io][5]
./node_modules/cliff/node_modules/winston/README.md:786:[5]: http://socket.io
./node_modules/winston/README.md:817:3. [socket.io][5]
./node_modules/winston/README.md:849:[5]: http://socket.io

**Comment by rajesh-rajagopal** [comment]
socket.io is not required. remove socket.io from vnc_server.
 require('socket.io');

**Comment by rajesh-rajagopal** [comment]
its fixed. close this issue.
